### PR TITLE
README: fix formatting - Markdown doesn't support dl/dt/dd notation of RDoc

### PR DESCRIPTION
**Pull request by aycabta**

### CODE REVIEW

**Review by olleolleolle — APPROVED** [review]
This indeed fixes the formatting in the README.

An alternative to making this a a list would be to format them as reference-style Markdown links:

```
[GNU Readline]: http://www.gnu.org/directory/readline.html
[libedit]: http://www.thrysoee.dk/editline/
```

...and to change the links to be `[Edit Line][libedit]` and [Gnu Readline][]`.


Another detail: `https://www.gnu.org/software/readline/` is what the directory link resolves to. And the last link also exists on https: `https://thrysoee.dk/editline/`

**Comment by aycabta** [comment]
README.md is also used by [RDoc document](https://www.rubydoc.info/gems/readline-ext), so it should be original Markdown syntax, not GitHub Flavored Markdown syntax.

**Comment by aycabta** [comment]
Ah...I see what you're getting at. I won't use the reference links for them. One introduction to those links is enough.

Also, I think the string `GNU Readline` shouldn't be a link, because there are some links to the `Readline` module and would be confusing.

**Comment by aycabta** [comment]
This is off-topic, but I am dealing with OSS in between my busy work schedule, I get exhausted when I am rushed by "approve". Can't you simply comment?

**Comment by olleolleolle** [comment]
@aycabta Sure! Thanks for telling me. Many projects are configured to only allow merging after a "lgtm" mark (Approve), so I guess I do that out of habit.

**Pull request merged**
